### ISSUE TITLE
seed artist URLs to MB artist

### ISSUE THREAD

**Issue by UltimateRiff** [kellnerd/harmony#33]
one feature I miss from a-tisket is how it can seed an edit to add artist URLs from the services it supports to the MusicBrainz artist

**Comment by UltimateRiff** [comment]
one possible extension of this (and I don't know if it's even possible), perhaps Harmony could remember URLs for the same artist? like if I go through an artist's Spotify page and not all releases are available on all platforms, but between all the releases, Harmony finds releases from say, Apple Music, Deezer, and Tidal, then it could remember those links when adding URLs to artists later?

this could of course be solved like a-tisket has done it, and just show a link to add missing URLs on the follow-up page, but I think it could be useful to remember URLs between searches, in case one got missed

**Comment by kellnerd** [comment]
I'm implementing this for artists and labels based on my work for #49.

**Comment by kellnerd** [comment]
Released as part of [v2024.10.13](https://github.com/kellnerd/harmony/tree/v2024.10.13)
