### ISSUE TITLE
No support for geo.music.apple.com links

### ISSUE THREAD

**Issue by wileyfoxyx** [kellnerd/harmony#36]
When trying to put a geo.music.apple.com link, Harmony displays an error:
`No provider supports https://geo.music.apple.com/XX/album/_/1234567890?mt=1&app=music&ls=1&at=1000lHKX`
where XX is region code (e.g. US), and 1234567890 is the album's ID

**Comment by kellnerd** [comment]
I've added support for the "geo" subdomain (594dacb41a25fa588e300b549561db0b54d50823) and also made the provider accept old URLs where the actual numeric ID is prefixed by "id" literally (23b7da23d2a1176f3fe5909dec031ded5cf0add9), for example https://geo.itunes.apple.com/album/id1135913516

**Comment by kellnerd** [comment]
No wonder, I've only changed the code, but there hasn't been a deployment of a new version to the server since then :wink:

**Comment by wileyfoxyx** [comment]
Ah, fair enough, sorry about that

**Comment by kellnerd** [comment]
Now live in v2024.6.12.

P.S. For future reference you can check the version link in the footer to see which changes are already included in the deployed version. Or when you open one of the commit links above, you can now see the version tags which include it.
