### ISSUE TITLE
MusicBrainz provider

### ISSUE THREAD

**Issue by kellnerd** [kellnerd/harmony#49]
ID lookups are already working in [my development branch](https://github.com/kellnerd/harmony/tree/musicbrainz-provider), GTIN lookups still have to be implemented.

**Comment by phw** [comment]
From discussion at #15:

> > Is the MB provider also considered the solution for finding existing MB releases, so the user can be notified that a release already exists?

> That's the idea, at least for the GTIN this should work without additional effort.
> I haven't yet decided whether I want to also do MB lookups for the external links of the other providers like a-tisket does it.
> The more providers are used for the combined lookup, the more potentially useless requests would be sent to the MB API. Especially since most of the time people will probably import a specific release which is missing on MB rather than trying to import a release which may already exist on MB.

I nevertheless think it would be good to do this. Maybe add it behind an option if it should not run by default. Or at least do the lookup for the URL given. But digital releases are frequently added without GTIN. For one they are optional on e.g. Bandcamp. And even the services having it mandatory don't expose them to the user directly.

I frequently add releases from Bandcamp using the importer userscript. That it does lookup potentially existing releases by URL is tremendously useful.

Also I think Harmony should not just show existing MB releases and warn about them, but also allow to jump to the post submission page for each release MBID to allow the user to submit ISRCs, cover art or any other data that might be added in the future (e.g. artist links, adding missing service links to releases etc.).

**Comment by kellnerd** [comment]
Released as part of [v2024.10.13](https://github.com/kellnerd/harmony/tree/v2024.10.13)
