### ISSUE TITLE
Add support for d.ontun.es to submit ISRCs

### ISSUE THREAD

**Issue by lazybookwyrm** [kellnerd/harmony#56]
Currently Harmony gives you the option to use MagicISRC to submit ISRCs but MagicISRC doesn't submit any edit note saying where those ISRCs come from. Knowing what release ISRCs were added from is very important, so it'd be nice if we also had the option to use [d.ontun.es](https://d.ontun.es/) to submit ISRCs as it includes an edit note saying what release the ISRCs came from.

**Comment by kellnerd** [comment]
I agree that the edit notes are important, I am still waiting for https://github.com/kepstin/magicisrc/pull/14 to be merged and deployed to make us of it.

Unfortunately the d.ontun.es website can only be used when Spotify data is available, so I would prefer a general solution like MagicISRC to submit ISRCs with edit note.
That said, I wouldn't be opposed to add an alternative option for ISRCs from Spotify if someone is willing to implement it.
