### ISSUE TITLE
deezer api returns different release date than other platforms

### ISSUE THREAD

**Issue by quantenzitrone** [kellnerd/harmony#58]
### problem description

compare these:
- https://api.deezer.com/album/upc:739919148793 (https://api.deezer.com/album/385098657)
- https://www.deezer.com/us/album/385098657

the deezer page says 2017-05-17, the correct release date that all other streaming platforms have as well, but the deezer api returns 2022-12-09

my guess is that the track was only later added to deezer and deezer for whatever reason returns the upload date as the release date in the api

this is also not an issue with a single track, i have seen this in a lot of cases
if you want i can give more examples, they are relatively trivial to find

### suggested solution

- give release date from the deezer api less precedence or ignore it completely
- scrape deezer for the real release date
- contact deezer so they hopefully fix their api

**Comment by kellnerd** [comment]
Actually the situation is quite contrary, Deezer is most likely the only platform which has the correct release date in this case.
Please note that I mean the [release date as defined by MusicBrainz](https://musicbrainz.org/doc/Style/Release#Date) and not the _original_ release date of the earliest release from a release group.
Have a look at the ISRC TL-REW-22-32114 from this single, the 22 indicates that the ISRC was assigned in 2022, so this specific release has to be from 2022 (or later).
(Another trick to approximate the correct release date is to have a look at the numeric IDs which are assigned to them by the platforms, [Apple uses sequential IDs](https://community.metabrainz.org/t/feedback-and-support-thread-for-the-pulsewidth-a-tisket-instance/578459/244?u=kellnerd) for example.)

Deezers API generally has the correct release date while their website displays the original release date. ([This seems to be intended.](https://en.deezercommunity.com/features-feedback-44/api-album-endpoint-is-returning-wrong-release-date-75353))
Other providers rarely have the correct release date if it differs from the original release date.

**Comment by quantenzitrone** [comment]
Tidal seems to sometimes agree with Deezer on the different release date, but I haven't investigated this further.

**Comment by UltimateRiff** [comment]
can confirm that Deezer usually has better release data, especially on pre-streaming albums (i.e. albums originally released before streaming services were a thing). I won't say always, but quite often

**Comment by quantenzitrone** [comment]
I found some releases where tidal is the only one with a different date:
- https://harmony.pulsewidth.org.uk/release?spotify=5eqyEKP83JQt8Tyu8Xlfld&gtin=193036666453&deezer=&itunes=&tidal=&region=GB&ts=1726069354
- https://harmony.pulsewidth.org.uk/release?spotify=6XDFPgnhoii8GhwAD6vUQH&gtin=840092657016&deezer=&itunes=&tidal=&region=GB&ts=1726069441

Is this some kind of tidal exclusive early release?

**Comment by kellnerd** [comment]
Possibly, Tidal had exclusive contracts with artists in the past, but I am not familiar with the artist, so I can't say for sure. In case of date discrepancies I always try to investigate the original release date, check news and announcements to see how the dates might relate.

For examples like the last two, a metadata aggregator like Harmony can't do much more than showing the potential values. Only for way too early dates and extremely unlikely dates like the 1st January I plan to add warnings and not use them by default.
(There is no dedicated ticket for that yet, it is only one of my notes in #6.)

**Comment by quantenzitrone** [comment]
Alright I think this is resolved, maybe there should be a new issue on how to handle different release dates on streaming plaftorms.

**Comment by quantenzitrone** [comment]
i have an example of a really weird date from the deezer api
https://harmony.pulsewidth.org.uk/release?spotify=4UI3AJMEuqGWEXNAtXvz5T&gtin=199093543201&deezer=&itunes=&tidal=&region=GB&ts=1736649198

The deezer api returns 2024-12-25, even tho the deezer streaming page says 2025-01-07 like every other streaming platform including youtube and soundcloud.
Opinion?
