### ISSUE TITLE
Actions page artist link submission does not submit beatport artist URLs

### ISSUE THREAD

**Issue by phw** [kellnerd/harmony#75]
I have noticed that even if a lookup resolved against beatport and beatport artist links are available on the release lookup page, the actions page does not include those in artist link submission.

I don't have a test case anymore, as I added the beatport links to the artists already, but this happened for me on:

https://harmony.pulsewidth.org.uk/release?beatport=3757675&spotify=4YGTju8vgSfd7unczk8PsE&gtin=4260066225151&deezer=&itunes=&tidal=&region=GB&ts=1733224401

**Comment by phw** [comment]
Sorry, can't reproduce this anymore with a new case. If I encounter this again I'll avoid the edit and link the example.

**Comment by kellnerd** [comment]
I guess this is not a Beatport specific issue, but another case of #71 probably.
