### ISSUE TITLE
Remove ` - Single` & ` - EP` from release names automagically

### ISSUE THREAD

**Issue by UnviableFriend** [kellnerd/harmony#9]
Some services add these bits to the ends of release titles. Currently atisket automatically removes them from the titles.

**Comment by kellnerd** [comment]
Agreed that this should be removed, ideally in combination with setting the release group type instead. We just have to be careful not to change release titles legitimately ending in EP.
Do you know any services other than Apple Music / iTunes which are doing this?

**Comment by phw** [comment]
I'll do this as part of #15
